// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaajxdvbnboapdfmsevp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhYWp4ZHZibmJvYXBkZm1zZXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODE4NTIsImV4cCI6MjA2MzY1Nzg1Mn0.gqp7o74QyHyFsfWerzdXaJ5WMJAThxQ9OQ-wQxwpyfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);